{
  inputs,
  lib,
  pkgs,
  ...
}: let
  inherit (inputs.agentic-flake.lib) mkSkill mkInlineSkill;

  dropSkillFrontmatter = text: let
    frontmatterFence = "\n---\n";
  in
    lib.concatStringsSep frontmatterFence
    (lib.drop 1 (lib.splitString frontmatterFence text));

  sickdeckTopology = ''
    ## Host topology

    The sickdeck service, iOS simulators and Android emulators run on `rose`, a
    Mac reached over Tailscale, not on this host. Here `sickdeck` is a native
    remote client: `SICKDECK_SERVER_URL` is preset to rose's service, so commands
    drive rose's devices over the tailnet with no ssh wrapper, no token and no
    per-command flags. Screenshots, recordings and `--stdout` output land on
    this host, written by the client. The browser launchpad is served by rose at
    http://rose:4310.

    `install` is the exception: it sends the path as a string for rose to
    resolve on its own filesystem, so a build sitting on this host is not
    reachable. Copy it to rose first, then pass the path it has there.
  '';
in {
  programs.agents = {
    enable = true;

    defaultScopes = ["common" "claude"];

    skills = with pkgs.agent-skills; [
      (mkInlineSkill {
          "nixgrep" = {
            description = "Search nix derivations from the /nix/store";
            tags = ["utils"];
            content = ''
              # Quick Reference

              $ nixgrep nao
              q0bfqrchwnip1n48idwmsblrqx3rds37-nao
              bsia93f0mzdrrdxigdmc48i9zcg2j4j7-nao-3.3.0
              298vl82bfm4939fd0clmw1m1hzid675j-nao-3.3.0-go-modules
              7gr2qa7saimqvnhl8nwgvlaf9fid25g9-nao-3.3.0-go-modules.drv
              rwajk54dm1wa3iqg0mahpv7bxhjyapfk-nao-3.3.0-go-modules.drv
            '';
          };
        } {
          plugins = ["nixgrep"];
        })
      (mkInlineSkill {
          "flake-update" = {
            description = "Update flake inputs in this dotfiles repo — bump nixpkgs, home-manager or any single input, then audit whether the pinned/patched overlays can be dropped, catch renamed or removed NixOS/home-manager options, and surface new upstream options and packages worth adopting. Use for any nix flake update, input bump or lock refresh.";
            tags = ["nix"];
            content = builtins.readFile ./skills/flake-update.md;
          };
        } {
          plugins = ["flake-update"];
        })
      (mkInlineSkill {
          "phone" = {
            description = "Drive the Android handsets and emulators on this desk with the `phone` CLI — pick a device, screenshot it, list the elements on screen, tap by name or coordinate, type, send keys, and handle split screen focus and foldable displays. Use for any hands-on Android device automation from this host.";
            tags = ["mobile"];
            content = builtins.readFile ./skills/phone.md;
          };
        } {
          plugins = ["phone"];
        })
      (anthropics.skills {
        prefix = "anthropics-";
        plugins = [
          "pdf"
          "pptx"
          "frontend-design"
        ];
      })
      (daffy0208.ai-dev-standards {
        plugins = [
          "mobile-developer"
        ];
      })
      (wshobson.agents {
        plugins = [
          "typescript-advanced-types"
          "e2e-testing-patterns"
        ];
      })
      (mkSkill {src = inputs.herdr;} {
        plugins = ["herdr"];
      })
      (mkInlineSkill {
          "sickdeck" = {
            description = "Drive iOS simulators and Android emulators on the remote mac rose — lifecycle, app install/launch, live viewing, UI inspection, touch/keyboard automation, screenshots, recordings, logs, pasteboard, hardware controls, and repeatable flows.";
            tags = ["mobile"];
            # Generated by the binary, so the guide cannot describe a CLI
            # surface the deployed build does not have.
            content = sickdeckTopology + dropSkillFrontmatter (builtins.readFile "${pkgs.sickdeck.skill}/SKILL.md");
          };
        } {
          plugins = ["sickdeck"];
        })
      (mkSkill {
          src = pkgs.fetchFromGitHub {
            owner = "aia-11-hn-mib";
            repo = "mib-mockinterviewaibot";
            rev = "50ccfb29063bb6d64d049fc982ca53424d0ca3b1";
            sha256 = "sha256-FdlbFVFSEtiFMiuisSLmgibFCro17jo3TjS9Oibx8F0=";
          };
        } {
          plugins = ["imagemagick"];
        })
      (mkSkill {
          src = pkgs.fetchFromGitHub {
            owner = "0xc000022070";
            repo = "skills";
            rev = "a6a17b6cd618ab3e0c38f5d7e4f44e98fa4ac1dd";
            sha256 = "sha256-+aFvj3qdCsn2wWW8C5QhAwR2hsYqcVBefBsb82J7Unw=";
          };
        } {
          plugins = [
            "android-firmware-lab"
            "voice-orchestrator"
          ];
        })
    ];
  };
}
