
latest_git_tag := `if test -d ".git"; then git describe --tags --abbrev=0; fi`
latest_git_commit := `if test -d ".git"; then git rev-parse origin/main; fi`

alias start := run

run: build
    ./build/program

build dst='./build/program':
    @go build -ldflags="-X main.version={{latest_git_tag}} -X main.commit={{latest_git_commit}}" -o {{dst}} ./
