# This file by default is chmod 600, so only the owners
# can read/write this file
{
  geoLocationServiceApiKey = "<api-key-here>";
  spotifyPassword = "<password-here>";

  openai = {
    organization-id = "<organization-id-here>";
    secret-key = "<secret-key-here>";
  };

  # The same configuration generated by 'rclone config'
  # https://rclone.org/drive/
  rclone = {
    aws = ''
      [aws]
      <config-here>
    '';

    drive = ''
      [drive]
      <config-here>
    '';

    custom = ''
      [<custom>]
      <config-here>
    '';
  };
}
