# This file by default is chmod 600, so only the owners
# can read/write this file
let
  secrets = rec {
    geoLocationServiceApiKey = "<api-key-here>";
    spotifyPassword = "<password-here>";

    openaiOrganizationId = "<organization-id-here>";
    openaiSecretKey = "<secret-key-here>";

    # The same configuration generated by 'rclone config'
    # https://rclone.org/drive/
    rclone = {
      aws = ''
        [aws]
        <config-here>
      '';

      drive = ''
        [drive]
        <config-here>
      '';

      custom = ''
        [<custom>]
        <config-here>
      '';
    };
  };
in
  secrets
