{
  inputs,
  system,
  ...
}:
with inputs; [
  (_final: _prev: {
    home-manager = home-manager.packages.${system}.home-manager.overrideAttrs (old: {
      buildCommand =
        old.buildCommand
        + ''
          substituteInPlace $out/bin/home-manager \
            --replace-fail "    presentNews" "    :"
        '';
    });
  })
  (_final: _prev: {
    llm-agents = llm-agents.packages.${system};
  })
  (final: _prev: let
    version = "0.1.33";

    # On non-darwin `build.rs` compiles only `native_stubs.c`, so none of the
    # x264 or Apple SDK machinery the mac build needs applies here. protoc is
    # not vendored, hence protobuf.
    server = final.rustPlatform.buildRustPackage {
      pname = "sickdeck-server";
      inherit version;

      src = sickdeck;
      # git+ssh inputs realise as `<hash>-source`, which is what unpackPhase
      # strips the store path down to.
      sourceRoot = "source/packages/server";
      cargoLock.lockFile = "${sickdeck}/packages/server/Cargo.lock";

      nativeBuildInputs = [final.protobuf];

      # The suite is darwin-gated in places and this host only consumes the
      # client; the fork's own CI is where it runs.
      doCheck = false;
    };
  in {
    # The Rust binary is the whole CLI here (clap `bin_name = "sickdeck"`): the
    # node launcher and bundled client the mac build assembles only matter to a
    # host that serves the launchpad.
    sickdeck = final.stdenvNoCC.mkDerivation {
      pname = "sickdeck";
      inherit version;

      dontUnpack = true;

      # `skill` holds the agent skill document, generated by the binary itself
      # so it cannot drift from the CLI surface it describes.
      outputs = ["out" "skill"];

      installPhase = ''
        runHook preInstall

        install -Dm755 ${server}/bin/sickdeck-server $out/bin/sickdeck

        mkdir -p $skill
        $out/bin/sickdeck skill-md > $skill/SKILL.md

        runHook postInstall
      '';
    };
  })
  hyprdysmorphic.overlays.default
  nixpkgs-extra.overlays.default
  agentic-flake.overlays.default
  hermes-agent.overlays.default
  inputs.herdr.overlays.default
  clipz.overlays.default
]
