{
  imports = [
    ./terminal
    ./desktop
    ./editors
    ./dev

    ./password-store.nix
    ./file-manager.nix
    ./color-picker.nix
    ./monitoring.nix
    ./gsimplecal.nix
    ./management.nix
    ./recording.nix
    ./macchina.nix
    ./discord.nix
    ./browser.nix
    ./torrent.nix
    ./zathura.nix
    ./ntfy-sh.nix
    ./spotify.nix
    ./for-fun.nix
    ./docker.nix
    ./btop.nix
    ./nao.nix
    ./bat.nix
    ./xdg.nix
  ];
}
