{
  dunstify-brightness,
  dunstify-sound,
  cliphist-rofi,
  spotify-dbus,
  rofi-radio,
  grimblast,
  pkgs,
  lib,
  ...
}: let
  # ugly, improve it
  binds = import ./binds.nix {
    inherit
      dunstify-brightness
      dunstify-sound
      cliphist-rofi
      spotify-dbus
      rofi-radio
      grimblast
      pkgs
      ;
  };

  exec = [
    "pkill waybar & sleep 0.1 && waybar"
  ];

  exec-once = [
    "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP"
  ];

  listToPrefixedLines = prefix: list: lib.strings.concatMapStrings (b: prefix + b + "\n") list;
in {
  # More keysyms here: https://github.com/xkbcommon/libxkbcommon/blob/master/include/xkbcommon/xkbcommon-keysyms.h
  xdg.configFile."hypr/hyprland.conf".text = ''
    ${listToPrefixedLines "exec-once = " exec-once}

    autogenerated = 0
    monitor=,highrr,auto,1
    env = XCURSOR_SIZE,24

    # For all categories, see https://wiki.hyprland.org/Configuring/Variables/
    input {
        numlock_by_default = true
        sensitivity = 0.2

        kb_layout = latam
        kb_variant =
        kb_model =
        kb_options =
        kb_rules =

        follow_mouse = 1

        touchpad {
            natural_scroll = no
            disable_while_typing = no
        }
    }

    general {
        # See https://wiki.hyprland.org/Configuring/Variables/ for more
        layout = dwindle

        gaps_in = 4
        gaps_out = 20
        border_size = 1

        # rgba(33ccffee) rgba(00ff99ee) 45deg
        col.active_border = rgba(595959aa)
        col.inactive_border = rgba(595959aa)
    }

    misc {
        disable_hyprland_logo = true
    }

    decoration {
        # See https://wiki.hyprland.org/Configuring/Variables/ for more
        rounding = 4

        blur {
            enabled = true
            size = 3
            passes = 1
        }

        # multisample_edges = true

        active_opacity = 0.9
        inactive_opacity = 1.0
        fullscreen_opacity = 1.0

        drop_shadow = yes
        shadow_range = 4
        shadow_render_power = 3
        col.shadow = rgba(1a1a1aee)
    }

    animations {
        enabled = yes

        # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

        bezier = myBezier, 0.05, 0.9, 0.1, 1.05

        animation = windows, 1, 7, myBezier
        animation = windowsOut, 1, 7, default, popin 80%
        animation = border, 1, 10, default
        animation = borderangle, 1, 8, default
        animation = fade, 1, 7, default
        animation = workspaces, 1, 6, default
    }

    dwindle {
        # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
        pseudotile = yes
        preserve_split = yes
    }

    master {
        # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
        new_is_master = true
    }

    gestures {
        # See https://wiki.hyprland.org/Configuring/Variables/ for more
        workspace_swipe = off
    }

    # Example per-device config
    # See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
    device:epic-mouse-v1 {
        sensitivity = -0.5
    }


    # Example windowrule v1
    # windowrule = float, ^(kitty)$
    # Example windowrule v2
    # windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
    # See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

    # See https://wiki.hyprland.org/Configuring/Keywords/ for more
    $mainMod = SUPER

    ${listToPrefixedLines "exec = " exec}

    ${listToPrefixedLines "bind = " binds.bind}
    ${listToPrefixedLines "bindm = " binds.bindm}
  '';
}
