{
  imports = [
    ./core
    ./desktop
    ./programs/browser/chromium.nix
    ./programs/compression.nix
    ./programs/development
    ./programs/gaming
    ./programs/network
    ./programs/package-managers
    ./programs/peripherals
    ./programs/security
    ./programs/shell
    ./programs/vm
    ./hardware
    ./boot
    ./fs
  ];
}
