self: let
  inherit (import ./binds.nix self) mainMod binds mouseBinds;

  window = import ./window.nix;
  exec = import ./exec.nix self;

  rules = ''
    autogenerated = 0
    # monitor=,highrr,auto,1
    monitor=,preferred,auto,1,mirror,eDP-1
    env = XCURSOR_SIZE,24

    input {
        numlock_by_default = true
        sensitivity = 0.2

        kb_layout = latam
        kb_variant =
        kb_model =
        kb_options =
        kb_rules =

        follow_mouse = 1

        touchpad {
            natural_scroll = no
            disable_while_typing = no
        }
    }

    misc {
        disable_autoreload = true
        disable_hyprland_logo = true
        focus_on_activate = false
        new_window_takes_over_fullscreen = 1
        initial_workspace_tracking = 2
    }

    dwindle {
        # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
        pseudotile = yes
        preserve_split = yes
    }

    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    master {
      new_status = master
    }

    gestures {
        workspace_swipe = off
    }

    device {
        name = epic-mouse-v1
        sensitivity = -0.5
    }
  '';

  listToPrefixedLines = prefix: list: self.lib.strings.concatMapStrings (b: prefix + b + "\n") list;
in {
  # More keysyms here: https://github.com/xkbcommon/libxkbcommon/blob/master/include/xkbcommon/xkbcommon-keysyms.h
  xdg.configFile."hypr/hyprland.conf".text = ''
    ${listToPrefixedLines "exec-once = " exec.once}

    ${rules}
    $mainMod = ${mainMod}

    general {
      ${window.general}
    }

    decoration {
      ${window.decoration}
    }

    animations {
      ${window.animations}
    }

    ${listToPrefixedLines "windowrulev2 = " window.rulesv2}

    ${listToPrefixedLines "exec = " exec.always}
    ${listToPrefixedLines "bind = " binds}
    ${listToPrefixedLines "bindm = " mouseBinds}
  '';
}
